#define NETWORK_SSID "<SSID>"
#define NETWORK_PASSWORD "<PASSWORD>"

#define MQTT_SERVER "<SERVER>"
#define MQTT_SERVER_PORT 0
#define MQTT_USERNAME "<USERNAME>"
#define MQTT_PASSWORD "<PASSWORD>"
#define MQTT_TOPIC "<TOPIC>"
#define TARGET "<TARGET"
